### ISSUE TITLE
Review info exposed through healthz/status endpoint

### ISSUE THREAD

**Issue by caproven** [sassoftware/event-provenance-registry#46]
Endpoint gives app-specific info but also includes info about the host (hostname, network interfaces including IPs, memory usage, cores) which I question the security of.

Should review all information provided through the endpoint & remove anything that doesn't need to be there.

I'll also note that the top level `host` & `port` fields are left blank and should either be filled out or removed.

**Comment by xbcsmith** [comment]
The intent is for this endpoint to be behind auth once we implement it. Also the other intent of the endpoint would be that we ship this information to a Status service that can provide us observability across the services.

**Comment by caproven** [comment]
Thank you for clarifying. Even behind auth I think some data could be removed such as network config but the issue exists to review all this content, if you're fine leaving it to be revisited later.

I personally believe CPU & memory metrics should be left to the orchestration platform, however I don't feel strongly either way. At the very least I'd like to see CPU details like # of cores & model name removed.

**Comment by xbcsmith** [comment]
Can I hide all the Downward API info behind the debug flag? Or maybe its own flag? Then a normal deployment would have minimal information available on the endpoint.

**Comment by caproven** [comment]
IMO the debug flag should influence logging, not behavior. If we did hide info based on a flag then I'd suggest it control a dedicated field in the resp (like `debugInfo`). That way it'd be clear when it's included or not, should any downstream scripting try to make assumptions about the schema.

**Comment by xbcsmith** [comment]
Agreed. How about --status-debug? Pretty specific. If not then I will rip the info block out and go back to a minimum status. Probably axe db config as well

**Comment by caproven** [comment]
I still feel the info should be ripped out, keeping the resp minimal & app specific. If you feel strongly about keeping this info in, then I'd propose keeping it all under `--debug`. When saying

> it'd be clear when it's included or not

I meant from the perspective of someone parsing the resp body, not someone running the server. I'm also thinking about this from a k8s perspective where resource & network monitoring are likely handled by separate tooling. When all you have is a hammer, everything looks like a nail.

**Comment by xbcsmith** [comment]
Based on this discussion I am removing the Downward API info from the status PR #44
