### ISSUE TITLE
Add functional tests for REST API

### ISSUE THREAD

**Issue by ninjamast3r** [sassoftware/event-provenance-registry#47]
Need some functional tests to exercise our REST endpoints so we can catch regressions.

**Comment by caproven** [comment]
Currently working on this - I'm going down the path of using build constraints (tags) on test files to mark a suite of functional tests not run by default.

**Comment by caproven** [comment]
Was a while back but closing issue as #80 was merged which added e2e REST tests. For posterity, we decided on e2e tests as functional tests seemed more trouble than they were worth.
