### ISSUE TITLE
feat: expand GraphQL search fields

### ISSUE THREAD

**Issue by xbcsmith** [sassoftware/event-provenance-registry#50]
Currently we only support ID we should expand that to support more properties

Events:
- ID
- Name
- Version 
- Release
- PlatformID
- Package

EventReceivers:
- ID
- Name
- Version
- Type
- Fingerprint

EventReceiverGroups:
- ID
- Name
- Version
- Type

**Comment by gbuskey** [comment]
Now returns a list of things, but does not include the additional requested parameters

**Comment by xbcsmith** [comment]
Need to clean pointer shenanigans as part of this Issue

**Comment by caproven** [comment]
If we *need* slice-pointers, at least keep them out of the storage pkg. Resolvers can hit storage methods and indirect further as necessary.

Alternatively can make schema arrays non-null, e.g., `event_receivers(id: ID!): [EventReceiver]!`. Then you are safe to return slices directly. This makes the query signature ambiguous for get-by-id scenarios; if an id doesn't exist, is that an error or do I get an empty array? To cover that, I'd suggest a dedicated id query:
```gql
type Query {
  # If no receivers meet criteria, should return empty (but not-null)
  # Later expand for pagination
  event_receivers(input: <input type>): [EventReceiver]!
  find_event_receiver(id: ID!): EventReceiver
}
```
Idk graph best practices but that seems most intuitive to me.

**Comment by xbcsmith** [comment]
#82
