### ISSUE TITLE
refactor: change logger verbosity levels to consts

### ISSUE THREAD

**Issue by xbcsmith** [sassoftware/event-provenance-registry#64]
We should  change logger verbosity levels to constants

logger.V(1).Info("Check Readiness : %s\n", content)

becomes

logger.Debug("Check Readiness : %s\n", content)

**Comment by caproven** [comment]
EPR's logging is pretty straightforward so I think this'd be fine, but let me be pedantic for a second.

I'd say this runs contrary to the philosophy of go-logr, see their README (specifically [why v levels](https://github.com/go-logr/logr/blob/master/README.md#why-v-levels)). For the sake of argument here's a case _not_ permitted (or at least muddied) by explicit levels:

```go
func main() {
	// omitting logger setup
	log.Info("standard info msg")
	doWork(log.WithName("default-verbosity-worker"))
	doWork(log.WithName("higher-verbosity-worker").V(1))
}

func doWork(l logr.Logger) {
	l.Info("doing some work")
}
```

```
level=0 msg="standard info msg"                              
level=0 logger=default-verbosity-worker msg="doing some work"
level=1 logger=higher-verbosity-worker msg="doing some work"
```

**Comment by xbcsmith** [comment]
This is currently low priority because there is not much usage of debug messaging in EPR currently

**Comment by ninjamast3r** [comment]
Went in a slightly different direction. We converted to using slog which makes this irrelevant.
